name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write # Required for requesting the JWT from AWS
  contents: read  # Required for actions/checkout

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./project-1-terraform-elastic-infrastructure
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # REPLACE with the ARN you got from your bootstrap apply
          role-to-assume: arn:aws:iam::696715200275:role/GitHubActionsRole
          aws-region: us-east-2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        # We pass the secrets into Terraform using the TF_VAR_ prefix
        env:
          TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
          TF_VAR_allowed_ip: ${{ secrets.ALLOWED_IP }}
        run: terraform plan -no-color

      - name: Terraform Apply
        # Only runs when code is merged into the main branch
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
          TF_VAR_allowed_ip: ${{ secrets.ALLOWED_IP }}
        run: terraform apply -auto-approve -input=false