name: Terraform CI

on:
  push:
    branches: [ main ]

permissions:
  id-token: write # CRITICAL for OIDC
  contents: read  # Allow reading the code

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Paste the ARN you got from the bootstrap output here
          role-to-assume: arn:aws:iam::696715200275:role/GitHubActionsRole
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan